apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meuapp
  name: meuapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meuapp
  template:
    metadata:
      labels:
        app: meuapp
    spec:
      containers:
      -  image: meuapp:1.0.0
         name: meuapp
         env:
          - name: NAME
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: NAME
